name: "Pull Requests"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - name: semantic-pull-request
        uses: amannn/action-semantic-pull-request@v3.4.0
        with:
          # Configure which types are allowed.
          # Default: https://github.com/commitizen/conventional-commit-types
          types: |
            fix
            feat
            lang
            build
            test
            refactor
            chore
            hotfix
            docs
            style
            perf
          # Configure which scopes are allowed.
          scopes: |
            processes
            activities
            tasks
            cases
            comments
            roles
            users
            files
            forms
            components
            labels
          # Configure that a scope must always be provided.
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
