on:
  workflow_dispatch:
    # inputs:
    #   buildtag:
    #     description: "postfix"
    #     required: true
    #     default: "beta"

name: Versioning

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: changelog
        uses: TriPSs/conventional-changelog-action@v3

        with:
          github-token: ${{ secrets.github_token }}
          tag-prefix: "v"
          skip-commit: "true"
          skip-version-file: "true"
          skip-on-empty: false

      - run: echo "RELEASE_VERSION=${{ steps.changelog.outputs.tag }}"

      - name: Build Docker Test
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: echo "RELEASE is ${{ steps.changelog.outputs.tag }}"
